- src/action/quickbooks.action.ts
- src/app/api/core/models/User.model.ts
- src/app/api/core/types/auth.ts
- src/app/api/core/types/client.ts
- src/app/api/core/types/invoice.ts
- src/app/api/core/types/notification.ts
- src/app/api/core/types/user.ts
- src/app/api/core/types/webhook.ts
- src/app/api/notification/notification.helper.ts
- src/app/api/notification/notification.service.ts
- src/app/api/quickbooks/auth/auth.service.ts
- src/app/api/quickbooks/invoice/invoice.helper.ts
- src/app/api/quickbooks/webhook/webhook.service.ts
- src/hook/useDashboard.ts
- src/hook/useQuickbooks.ts
> Code refactor

- package.json
- supabase/config.toml
- created a script command that ignores the unhealthy services (for dev). Seems to have this vector image issue in latest supabase version. Workaround to avoid downgrading the supabase version. This doesn't affect the production environment.
- supabase storage config disabled
> Supabase local issues

- .env.example
- src/app/api/quickbooks/customer/customer.service.ts
- src/app/api/quickbooks/invoice/invoice.service.ts
- src/app/api/quickbooks/token/token.service.ts
- src/db/migrations/0008_qb_customers_table.sql
- src/db/migrations/0009_datatype_change_for_client_id.sql
- src/db/migrations/meta/0008_snapshot.json
- src/db/migrations/meta/0009_snapshot.json
- src/db/migrations/meta/_journal.json
- src/db/schema/index.ts
- src/db/schema/qbCustomers.ts
- src/type/dto/intuitAPI.dto.ts
- src/utils/intuitAPI.ts
- mapping table 
- update user with old full name in detail
[Loom](https://www.loom.com/share/d288ef71b5354fdeb977a7fd0bee0bbd?sid=73e55d4b-97f9-4ba4-b590-7e89b70ebb14)
> OUT-1748 | Customer update in QB if change in copilot side

- src/app/api/quickbooks/product/map/route.ts
- src/app/api/quickbooks/product/product.controller.ts
- src/app/api/quickbooks/product/product.service.ts
- src/components/dashboard/settings/SettingAccordion.tsx
- src/components/dashboard/settings/sections/product/ProductMapping.tsx
- src/components/dashboard/settings/sections/product/ProductMappingTable.tsx
- src/db/schema/qbProductSync.ts
- src/hook/useSettings.ts
[Loom](https://www.loom.com/share/c06934ea08d946968513e94ada85db60?sid=d2f6bfe4-172b-43f1-9ed7-700d23b1c7a4)
> Out 1821 | List mapped items in table and update on confirm

- src/app/(home)/Home.tsx
- src/app/context/AuthContext.tsx
- src/hook/useDashboard.ts
- src/hook/useQuickbooks.ts
[Loom](https://www.loom.com/share/4e4ecb41cdc5416a919a8e99e5e25e4d)
> Out 1806 | Proper messages in callout with CTA

- src/hook/useSettings.ts
- refactor: removed else block and normal return
> refactor(OUT-1821): conditional return

- src/app/api/quickbooks/invoice/invoice.service.ts
- src/db/migrations/0016_removed_doc_number_column_from_invoice_sync.sql
- src/db/migrations/meta/0016_snapshot.json
- src/db/migrations/meta/_journal.json
- src/db/schema/qbInvoiceSync.ts
[Loom](https://www.loom.com/share/df7b4f8ec37a44f3bab6758fd49fe3fc?sid=4210fd44-281f-4a42-8a1a-c61ebbf6c068)
> OUT-1861 | Invoice number is not being synced

- src/app/api/core/types/invoice.ts
- src/app/api/core/types/webhook.ts
- src/app/api/quickbooks/invoice/invoice.service.ts
- src/app/api/quickbooks/webhook/webhook.service.ts
- src/db/migrations/0022_add_deleted_to_invoice_statuses.sql
- src/db/migrations/meta/0022_snapshot.json
- src/db/migrations/meta/_journal.json
- src/type/dto/intuitAPI.dto.ts
- src/type/dto/webhook.dto.ts
- src/utils/auth.ts
- src/utils/intuitAPI.ts
https://github.com/user-attachments/assets/9c36f131-a8bd-420c-819d-8dbea79b5217
> OUT-1836 | Implementation for deleted invoices

- src/app/(home)/HomeClient.tsx
- src/bridge/header.ts
- src/config/index.ts
- src/constant/domains.ts
- src/hook/useQuickbooks.ts
[Loom](https://www.loom.com/share/c860e239818b422cb7004d832ac20e4d?sid=8980d97c-901c-4df7-bd08-378682063c13)
> OUT-1920: Manual disconnect of the app

- .env.example
- src/app/api/quickbooks/cron/cron.controller.ts
- src/app/api/quickbooks/cron/cron.service.ts
- src/app/api/quickbooks/cron/route.ts
- src/app/api/quickbooks/sync/sync.service.ts
- src/config/index.ts
- src/db/service/token.service.ts
- src/utils/crypto.ts
- vercel.json
[Loom](https://www.loom.com/share/fe0c9f068f0d4408b9d5cbcb0cb534f6?sid=38b7935c-2a87-4701-8edf-7e7a74ad6082)
> OUT-1960: Create cron job to re-sync failed sync logs

- src/components/dashboard/settings/SettingAccordion.tsx
> OUT-1977: button label change

- src/components/dashboard/settings/sections/product/ProductMappingTable.tsx
- src/hook/useSettings.ts
[Loom](https://www.loom.com/share/546208a1c3bc4a4c9a686b0f60dc5f4c?sid=c1de383e-c381-4fe0-8ca3-cd1535110a05)
> OUT-1974: improve syncing with Quickbooks feedback

- src/app/api/quickbooks/invoice/invoice.service.ts
- src/app/api/quickbooks/product/product.controller.ts
- src/components/dashboard/settings/sections/product/ProductMappingTable.tsx
- src/hook/useSettings.ts
- src/type/common.ts
- src/type/dto/webhook.dto.ts
[Loom](https://www.loom.com/share/8f3d99b358f345d49228337fcdf25442?sid=1bee96d1-0de0-4f1b-8eed-3b861ca43d1e)
- Price format fix
> OUT-2025: QB item's price is not mapping for the product

- src/app/api/quickbooks/product/product.service.ts
> OUT-1798: Sort product list by price in ascending order

- src/app/(home)/HomeClient.tsx
- src/app/api/quickbooks/auth/auth.controller.ts
- src/app/api/quickbooks/auth/auth.service.ts
- src/app/api/quickbooks/auth/connection-error/route.ts
- src/app/error.tsx
- src/app/quickbooks/callback/page.tsx
- src/hook/useDashboard.ts
- src/hook/useQuickbooks.ts
[Loom](https://www.loom.com/share/2b99853ecc91400e9a42ed88274a8ec5?sid=a78870c3-9aec-4dd2-ba48-fb6ce92c5507)
> OUT-2028: UI improvements for initial connection and re-auth

- src/app/api/quickbooks/invoice/invoice.service.ts
- src/app/api/quickbooks/setting/setting.controller.ts
- src/components/dashboard/settings/sections/product/ProductMapping.tsx
- src/db/migrations/20250723150127_remove_create_invoice_item_flag.sql
- src/db/migrations/meta/20250723150127_snapshot.json
- src/db/migrations/meta/_journal.json
- src/db/schema/qbSettings.ts
- src/hook/useSettings.ts
- src/type/common.ts
[Loom](https://www.loom.com/share/494435f4b6f9479da9043e35443be88e?sid=de4de27a-6cbc-41a8-9725-50f01cfae009)
> OUT-2057: Merge "Product Mapping" settings into a single setting

- src/bridge/header.ts
- src/hook/useQuickbooks.ts
> OUT-2050 | OUT-2093 | UX Fixes for Quickbooks Integration

- src/hook/useSettings.ts
[Loom](https://www.loom.com/share/c68430a93c104186a5cbca6dc2c2d206?sid=50d79173-dabd-4774-bf6b-fe6b7604be1e)
> OUT-2088: Optimistically hide update sync button

- src/app/api/core/types/webhook.ts
- src/app/api/quickbooks/invoice/invoice.service.ts
- src/app/api/quickbooks/product/product.service.ts
- src/app/api/quickbooks/webhook/webhook.service.ts
- src/db/migrations/20250730125312_add_copilot_name_column_in_product_sync.sql
- src/db/migrations/meta/20250730125312_snapshot.json
- src/db/migrations/meta/_journal.json
- src/db/schema/qbProductSync.ts
- src/hook/useSettings.ts
- src/utils/string.ts
> OUT-2108: Potential fix for products are occassionally not being created

- src/components/dashboard/settings/sections/product/ProductMappingTable.tsx
- src/hook/useDropdown.ts
[Loom](https://www.loom.com/share/1bb31fe7dbb84395be1c5c274a02017a?sid=26e63dcd-993e-45cb-843e-44d6d53d7ba8)
> OUT-2100: Dropdowns extend beyond screen content

- src/app/api/quickbooks/product/product.controller.ts
- src/app/api/quickbooks/product/product.service.ts
- src/db/schema/qbProductSync.ts
> OUT-2111: multiple prices mapping, unlink the existing price and product

- src/hook/useQuickbooks.ts
> OUT-2123: removed header menu icons as a temporary fix

- src/components/dashboard/settings/sections/product/ProductMappingTable.tsx
> OUT-2124: implemented word break for long QB product name

- src/app/api/quickbooks/invoice/invoice.service.ts
- src/app/api/quickbooks/payment/payment.service.ts
- src/app/api/quickbooks/sync/sync.service.ts
- src/app/api/quickbooks/webhook/webhook.service.ts
- src/utils/error.ts
> OUT-2120: added missing error message in sync log history

- src/app/api/core/constants/limit.ts
- src/app/api/quickbooks/invoice/invoice.service.ts
- src/app/api/quickbooks/product/product.controller.ts
- src/app/api/quickbooks/product/product.service.ts
- src/components/dashboard/settings/sections/product/ProductMappingTable.tsx
- src/db/migrations/20250820090601_add_class_ref_to_product.sql
- src/db/migrations/meta/20250820090601_snapshot.json
- src/db/migrations/meta/_journal.json
- src/db/schema/qbProductSync.ts
- src/hook/useSettings.ts
[Loom](https://www.loom.com/share/bd1c7fb99b3449a08940cfe4ea50368f?sid=7ceebaa2-2c32-45ad-a7ce-025254bd9f45)
> OUT-2225: include Class reference of Item in invoice

- src/app/(home)/Home.tsx
- src/app/context/AppContext.tsx
- src/components/dashboard/settings/sections/invoice/InvoiceDetail.tsx
- src/db/service/token.service.ts
- src/type/common.ts
- src/utils/workspace.ts
> OUT-2230: Support custom client/company labels in the copy
